[package]
name = "eyelid-matcher"

# Configure in eyelid/Cargo.toml
edition.workspace = true
readme.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
eyelid-match-ops = { version = "0.1.0", path = "../eyelid-match-ops" }

[dev-dependencies]
eyelid-test = { path = "../eyelid-test" }
