[package]
name = "eyelid-match-ops"

# Configure in eyelid/Cargo.toml
edition.workspace = true
readme.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[features]

# Benchmark-only dependencies
benchmark = [
    "criterion",
    "lazy_static",
    "rand",
]

[dependencies]
ark-ff.workspace = true
ark-poly.workspace = true
ark-std.workspace = true
bitvec.workspace = true
static_assertions.workspace = true

# Benchmark-only dependencies
criterion = {workspace = true, optional = true}
lazy_static = {workspace = true, optional = true}
rand = {workspace = true, optional = true}

[dev-dependencies]
eyelid-test.workspace = true

lazy_static.workspace = true
rand.workspace = true

[lib]
bench = false

[[bench]]
name = "match-ops"
harness = false
required-features = ["benchmark"]

[lints]
workspace = true
