[package]
name = "eyelid-match-ops"

# Configure in eyelid/Cargo.toml
edition.workspace = true
readme.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ark-ff = "0.4.2"
ark-poly = "0.4.2"

[dev-dependencies]
eyelid-test = { path = "../eyelid-test" }
