[package]
name = "eyelid-match-ops"

# Configure in eyelid/Cargo.toml
edition.workspace = true
readme.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ark-ff.workspace = true
ark-poly.workspace = true

[dev-dependencies]
eyelid-test.workspace = true

[lints]
workspace = true
