[package]
name = "eyelid-test"

# Configure in eyelid/Cargo.toml
edition.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# Test-only configuration
publish = false

[dependencies]

[dev-dependencies]
criterion = { version = "0.5.1", default-features = false, features = ["cargo_bench_support", "rayon"] }
