name: 'Rust Benchmarks'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Benchmarks
        run: |
          export RUSTFLAGS="-D warnings"
          cargo bench --no-run --all-features --all-targets

      - name: Run Tests
        run: |
          export RUSTFLAGS="-D warnings"
          echo "Warning: benchmark timings are unreliable in CI due to virtualization"
          cargo bench --all-features --all-targets
          echo "Warning: benchmark timings are unreliable in CI due to virtualization"
