name: 'Rust Benchmarks'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    # Benchmarks have custom code to compare different functions, so we don't need to have a matrix here.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Benchmarks
      run: |
        export RUSTFLAGS="-D warnings"
        cargo bench --no-run --features benchmark --all-targets

    - name: Run Benchmarks
      run: |
        export RUSTFLAGS="-D warnings"
        echo "Warning: benchmark timings are unreliable in CI due to virtualization"
        cargo bench --features benchmark --all-targets
        echo "Warning: benchmark timings are unreliable in CI due to virtualization"
