name: 'Benchmarks'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  bench:
    name: Rust Benchmarks

    # Benchmarks have custom code to compare different functions, so we don't need a matrix here.
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - uses: r7kamura/rust-problem-matchers@v1

     - name: Build Benchmarks
       run: |
         export RUSTFLAGS="-D warnings"
         cargo bench --no-run --features benchmark --all-targets

     - name: Run Benchmarks
       run: |
         export RUSTFLAGS="-D warnings"
         echo "Warning: benchmark timings are unreliable in CI due to virtualization"
         cargo bench --features benchmark --all-targets
         echo "Warning: benchmark timings are unreliable in CI due to virtualization"
