name: 'Build and Run'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Rust Build and Run

    strategy:
      # We want to run tiny_poly to completion, so bugs are easier to diagnose
      fail-fast: false      
      matrix:
        # rustc config options
        cfg: ["", "--cfg tiny_poly"]
        # cargo feature options, "--no-default-features" is the same as "" for now
        features: ["", "--all-features"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: r7kamura/rust-problem-matchers@v1

      - name: Build All Targets
        run: |
          export RUSTFLAGS="-D warnings ${{ matrix.cfg}}"
          cargo build --release --all-targets ${{ matrix.features}}

      - name: Run Binaries
        run: |
          export RUSTFLAGS="-D warnings ${{ matrix.cfg}}"
          cargo run --release ${{ matrix.features}}
