name: 'Tests'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: Rust Tests

    strategy:
      matrix:
        # rustc config options
        cfg: ["", "--cfg tiny_poly"]
        # cargo feature options
        features: ["", "--no-default-features", "--all-features"]
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Tests
        run: |
          export RUSTFLAGS="-D warnings ${{ matrix.cfg}}"
          cargo test --no-run --all-targets ${{ matrix.features}}

      - name: Run Tests
        run: |
          export RUSTFLAGS="-D warnings ${{ matrix.cfg}}"
          cargo test --all-targets ${{ matrix.features}}

      # For historical reasons, Rust documentation tests are not run by `cargo test`.
      - name: Run Doc Tests
        run: |
          export RUSTFLAGS="-D warnings ${{ matrix.cfg}}"
          cargo test --doc ${{ matrix.features}}
