name: 'Clippy Lints'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  clippy:
    name: Check Rust Lints

    strategy:
      matrix:
        # rustc config options
        cfg: ["", "--cfg tiny_poly"]
        # cargo feature options
        features: ["", "--no-default-features", "--all-features"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clippy Lints
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets ${{ matrix.features}} -- -D warnings ${{ matrix.cfg}}
