name: 'Spell Check'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# If this workflow keeps failing, edit eyelid/.codespellrc to add more words to ignore,
# <https://github.com/codespell-project/actions-codespell#usage>
# or temporarily disable this workflow using the three dots next to "filter workflow runs" in the Actions tab
# <https://github.com/Inversed-Tech/eyelid/actions/workflows/lint-spell.yml>
jobs:
  codespell:
    name: Check Spelling

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
       
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          # setting this to any value will disable errors but keep annotations
          #only_warn: true
