name: 'Rust Docs'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# The actions variables and shell env namespaces are different, so we need to import every relevant variable here:
# <https://github.com/Inversed-Tech/eyelid/settings/variables/actions>
env:
  # Logging
  CARGO_TERM_COLOR: ${{ vars.CARGO_TERM_COLOR }}

jobs:
  docs:
    name: Check Docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: r7kamura/rust-problem-matchers@v1

      # "--all-features" covers "" and "--no-default-features" for now
      - name: Build docs
        run: |
          export RUSTDOCFLAGS="-D warnings"
          cargo doc --no-deps --workspace --all-features --document-private-items
