name: 'Clippy Lints'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# The actions variables and shell env namespaces are different, so we need to import every relevant variable here:
# <https://github.com/Inversed-Tech/eyelid/settings/variables/actions>
env:
  # Logging
  CARGO_TERM_COLOR: ${{ vars.CARGO_TERM_COLOR }}

jobs:
  clippy:
    name: Check Rust Lints

    strategy:
      # Most clippy errors will be duplicates, so we don't need to run to completion here
      matrix:
        # rustc config options
        cfg: ["", "--cfg tiny_poly"]
        # cargo feature options: "--all-features" covers "" and "--no-default-features" for now
        features: ["--all-features"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clippy Lints
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets ${{ matrix.features}} -- -D warnings ${{ matrix.cfg}}
