name: 'Rust Format'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# The actions variables and shell env namespaces are different, so we need to import every relevant variable here:
# <https://github.com/Inversed-Tech/eyelid/settings/variables/actions>
env:
  # Logging
  CARGO_TERM_COLOR: ${{ vars.CARGO_TERM_COLOR }}

jobs:
  bench:
    name: Check Rust Formatting

    # Active and inactive code is format checked, so we don't need a matrix here.
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4

      # Ensure rustfmt is installed, and set up problem matchers
     - uses: actions-rust-lang/setup-rust-toolchain@v1
       with:
         components: rustfmt

     - name: Check rustfmt
       uses: actions-rust-lang/rustfmt@v1
