name: 'Rust Docs'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  docs:
    name: Check Docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: r7kamura/rust-problem-matchers@v1

      - name: Build docs
        run: |
          cargo doc --no-deps --workspace --all-features --document-private-items