name: 'Spell Check'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  codespell:
    name: Check Spelling

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
       
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          only_warn: true
